### PR TITLE
Support for iOS 5

### PR DESCRIPTION
**Pull request by aporat**
contains changes from https://github.com/Sumi-Interactive/SIAlertView/pull/6 & fixes `UIWindow` hierarchy issues by saving a reference to the old `UIWindow`.

This pull request is more a hack than a fix, but it might help someone to the right direction.

### CODE REVIEW

**Comment by ricsantos** [comment]
This does not fix the z-layer issue (alert view is presented below the shadow). Also, does not address the rotation issue (alert view is presented in portrait device orientation).

**Comment by dmitrc** [comment]
Is this commit ready to use? Or some bugs are still there?
In case if the problem can't be solved without hacking, maybe we should incorporate fallback to UIAlertView for older firmwares right into the control?

**Comment by kyoji2** [comment]
Hey guys. SIAlertView is now support iOS 5. Thanks @aporat for the original pull request, and @steakknife for the trying to fix the windows hierarchy issue. Turns out it's a really easy way to achieve that. Check the commit history if you are interested.

**Comment by skull-squadron** [comment]
Awesome.  Will test.

**Pull request closed without merging**
