### PR TITLE
Add support to iOS 5 and lower

### PR DESCRIPTION
**Pull request by mrcrow**

### CODE REVIEW

**Comment by kyoji2** [comment]
The problem in iOS5 is: window hierarchy is mess up, the background window is over alert window.

**Comment by skull-squadron** [comment]
This almost works. :+1:   Good work.  (We're also stuck supporting iOS 5 for at least 9 more months.)

On a 5.0 device, the alert is appearing _below_ the fade effect.  Perhaps it's relying on new 6.0+ window hierarchy behavior for Z-ordering the views?  I think this is exactly what @kyoji2 referred to.

img

On a 6.0+ device, everything's fine.

img

**Comment by ricsantos** [comment]
For what it's worth, I am just checking the OS version and displaying SIAlertView or UIAlertView accordingly.

**Comment by skull-squadron** [comment]
Cool.  @aporat is pull #11 in a testable state?

**Comment by ricsantos** [comment]
Orientation is not supported properly in iOS 5.

**Comment by ricsantos** [comment]
Orientation support has now been added in pull #19.

**Pull request closed without merging**
